# Generated by Django 3.2.25 on 2025-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='entreprise',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
