# Generated by Django 3.2.25 on 2025-02-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0002_client_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
