# Generated by Django 3.2.25 on 2025-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='entreprise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
