# Generated by Django 3.2.25 on 2025-02-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0004_auto_20250209_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='training_programs/')),
            ],
        ),
    ]
