# Generated by Django 3.2.25 on 2025-02-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0005_trainingprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
