# Generated by Django 3.2.25 on 2025-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0006_client_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
